#version: "3"

services:
  # ==========================
  # Base de datos PostgreSQL
  # ==========================
  postgres:
    image: postgres:15
    container_name: postgres-tpfinal-programacion2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backendCatedra
      POSTGRES_USER: backendCatedra
      POSTGRES_PASSWORD: backendCatedra
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ==========================
  # Redis local (opcional)
  # ==========================
  redis:
    image: redis:8.0
    container_name: redis-tpfinal
    restart: unless-stopped
    ports:
      - "6379:6379"

  # ==========================
  # Zookeeper para Kafka
  # ==========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # ==========================
  # Kafka broker
  # ==========================
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
